env:
  apiEndpoint: "https://staging-public-api.zilkroad.io"
  network: testnet
  nftMarketplaceAddress: "0xad43392d1750771e58931801ddc274e5984660b4"
  wzilAddress: "0x864895d52504c388A345eF6cd9C800DBBD0eF92A"
  cdnBase: https://zildexr-testnet.b-cdn.net/
  taxAmount: "200"
  maxRoyaltyBps: "10000"
  docsUrl: 'https://docs-testnet.zilkroad.io/'
  
namespace: zilkroad-beta

image:
  app:
    pullSecret: aws-registry

ingress:
  host: testnet.zilkroad.io

replicas: 2

# filebeat requirements
logPath: /app/logs

elasticSearch:
  hosts:       https://search.zildexr.com:443
  username:    elastic
  password:    gyXGCRTvHuNjLKEXQUH98kggRLEfH6rP
