apiVersion: v1
kind: Service
metadata:
  name: client
  namespace: {{ .Values.namespace }}
  labels:
    service: client
spec:
  selector:
    service: client
  ports:
  - name: http
    port: {{ .Values.port }}
    targetPort: {{ .Values.targetPort }}
    protocol: TCP
