image:
  app: 
    url: 981130112916.dkr.ecr.us-east-1.amazonaws.com/zilkroad/client
    tag: latest
    pullPolicy: IfNotPresent
    pullSecret: ~

port: 3050
targetPort: 3050
namespace: devnet

logPath: /app/logs

replicas:
  client: 1

ingress:
  host: dev.zilkroad.io

env:
  viteApiEndpoint: "http://public-api:5000"
  nftMarketplaceAddress: "0x0000000000000000000000000000000000000000"
  wzilAddress: "0x0000000000000000000000000000000000000000"

resources:
  limits:
    cpu: 0.1
    memory: 128M
  requests:
    cpu: 0.1
    memory: 128M
