name: Lint and Build Client image

on:
  pull_request:
    branches: [ master ]
    paths:
      - 'client/**'

  # Allows manual trigger
  workflow_dispatch:

env:
  CONTAINER_NAME: client 
  IMAGE_TAG: ${{ github.sha }}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: hadolint/hadolint-action@v1.5.0
      with:
        dockerfile: client/Dockerfile
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build Docker image
      working-directory: ./client
      id: build-image
      run: |
        docker build -t $CONTAINER_NAME:$IMAGE_TAG .
