name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies 📦
        run: npm ci --legacy-peer-deps
      - name: Show Cypress information ℹ️
        run: npx cypress info
      - name: Verify Cypress can run 🏃‍♂️
        run: npx cypress verify
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          # Simply start a python http server that exposes the build/ dir
          start: python3 -m http.server --directory build 3000
          # Only start tests when the server is up and running.
          wait-on: http://localhost:3000/
          # A simple python http server should really never take longer
          # than 10 seconds to start.
          wait-on-timeout: 10
          record: true
        env:
          # pass GitHub token to detect new build vs re-run build
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          # overwrite commit message sent to Dashboard
          COMMIT_INFO_MESSAGE: ${{github.event.pull_request.title}}
          # re-enable PR comment bot
          COMMIT_INFO_SHA: ${{github.event.pull_request.head.sha}}

          CYPRESS_RECORD_KEY: ${{secrets.CYPRESS_RECORD_KEY}}
