name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    needs: build
    runs-on: ubuntu-20.04
       steps:
        - uses: actions/checkout@v2

        # Download the build from the previous step.
        - uses: actions/download-artifact@v2
          with:
            name: build
            path: build

        # Run all cypress tests.
        - name: Cypress run
          uses: cypress-io/github-action@v2
          with:
            # Simply start a python http server that exposes the build/ dir
            start: python3 -m http.server --directory build 3000
            # Only start tests when the server is up and running.
            wait-on: http://localhost:3000/
            # A simple python http server should really never take longer than 10 seconds to start.
            wait-on-timeout: 10
            # Record test artifacts
            record: true
          env:
            # pass GitHub token to detect new build vs re-run build
            GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
            # overwrite commit message sent to Dashboard
            COMMIT_INFO_MESSAGE: ${{github.event.pull_request.title}}
            # re-enable PR comment bot
            COMMIT_INFO_SHA: ${{github.event.pull_request.head.sha}}
            # puts the infomation on the webportal?
            CYPRESS_RECORD_KEY: ${{secrets.CYPRESS_RECORD_KEY}}
